### ISSUE TITLE
Demo mobile view broken

### ISSUE THREAD

**Issue by interludic** [hjzheng/angular-mega-menu#1]
Hi,

I am looking into using your mega-menu.

As you can kind of see when i click on the menu button nothing happens. is this an issue in the demo or in the code as well, i need to be able to use this responsively.
![capture](https://cloud.githubusercontent.com/assets/6327261/10567202/701623ec-7648-11e5-9e19-36e5ef235ddc.JPG)

**Comment by interludic** [comment]
Tested: Issue is in chrome and firefox dev.

**Comment by hjzheng** [comment]
Sorry, this angular directive not supported the mobile case, if you want support it, so far, you can use  yamm3 on https://github.com/geedmo/yamm3.

**Comment by hjzheng** [comment]
I will try to implement mobile case.

**Comment by hjzheng** [comment]
OK, It is fixed, you can try it again!
