### ISSUE TITLE
directive/service override prevent use of ui-dropdown elsewhere

### ISSUE THREAD

**Issue by kwesterfeld** [hjzheng/angular-mega-menu#5]
We are using uib-dropdown all over our application, and if we include the angular-mega-menu module for use in creating a mega menu, it prevents the close behavior of uib-dropdown in the application.

I tried to tweak the source but I cannot figure out how to make both work at the same time.  Something occurs related to the $document click handler.  

The behavior I am seeing is that when a user clicks any of the dropdown menus in the application, this module prevents the "close" behavior of the dropdown.

**Comment by hjzheng** [comment]
I fixed it, please try it again, use auto-close attribute to control the behavior.

**Comment by kwesterfeld** [comment]
Sorry, I will not have time to try this for a while.  I found a workaround in that the only behavior I wanted was the mouseover behavior, which I was able to simulate with is-open, ng-mouseenter and ng-mouseleave with a simple scope variable, placed on the &lt; li &gt;
