### ISSUE TITLE
Menu does not close when you click on a link

### ISSUE THREAD

**Issue by rossmc** [hjzheng/angular-mega-menu#6]
Hi, thanks for this plugin.

I noticed one thing though, when you click on a menu link it does not close the menu, which isn't great as with angularjs the content behind the menu often changes when you click a link like this without a page refresh, so the user may not see the menu page changing.

It's ocuring on your demo page too.

Thanks,

**Comment by hjzheng** [comment]
You want to close the menu when click on the menu link,  you can set `auto-close` attribute to `aways`.
```js  
 <li class="dropdown" uib-dropdown auto-close="always">
...
```

for more configuration, you can refer https://angular-ui.github.io/bootstrap/#/dropdown

**Comment by rossmc** [comment]
@hjzheng   thanks but that only closes the sub menu, not the entire menu, similarly to how the entire menu closes when you click on the icon bars.  This is how our menu looks...

	<div ng-controller="mainNavController as mainNavCtrl">
		<nav class="navbar navbar-default yamm" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle"
						ng-click="mainNavCtrl.isNavCollapsed = !mainNavCtrl.isNavCollapsed; mainNavCtrl.iconSwap()">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" uib-collapse="mainNavCtrl.isNavCollapsed">
				<ul class="nav navbar-nav">
					<li class="dropdown open" uib-dropdown auto-close="always" on-toggle="toggled(open)">
						<a href id="nav-1-1" class="dropdown-toggle" uib-dropdown-toggle toggle-event="mouseover">Link Text</a>
						<ul class="dropdown-menu" uib-dropdown-menu aria-labelledby="nav-1-1">
							<li>
								<div class="yamm-content container">
									<ul class="flex-justified">
										<li role="menuitem">
											<a href="/somewhere">Somewhere</a>
										</li>
										<li role="menuitem" ng-repeat="anchor in mainNavCtrl.anchorLinks">
											<a href="/somewhere#{{anchor}}">{{anchor}}</a>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</li>

**Comment by hjzheng** [comment]
you mean this icon, you want click this icon to close entire menu when click menu link.
![image](https://cloud.githubusercontent.com/assets/4166657/21873836/3a3929a0-d8ac-11e6-8ca1-219ff9dff3c1.png)

I think you can try to set the mainNavCtrl.isNavCollapsed to false in toggled function when open argument is false.

`<li class="dropdown open" uib-dropdown auto-close="always" on-toggle="toggled(open)">`
